DEBUG = True
SECRET_KEY = 'mysecretkey'
JWT_TOKEN_LOCATION = 'cookies'
JSON_AS_ASCII = False
JWT_COOKIE_SECURE = False
JWT_ACCESS_COOKIE_PATH = '/'
JWT_REFRESH_COOKIE_PATH = '/refresh'
JWT_COOKIE_CSRF_PROTECT = False